//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class pianta
    {
        public int Id { get; set; }
        public string nome { get; set; }
        public int taglia { get; set; }
        public bool ordinata { get; set; }
        public double prezzopianta { get; set; }
        public double prezzolavoro { get; set; }
    }
}
