//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progetto.PaesaggistaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="paesaggista", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class paesaggista : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cognomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int identificativoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cognome {
            get {
                return this.cognomeField;
            }
            set {
                if ((object.ReferenceEquals(this.cognomeField, value) != true)) {
                    this.cognomeField = value;
                    this.RaisePropertyChanged("cognome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int identificativo {
            get {
                return this.identificativoField;
            }
            set {
                if ((this.identificativoField.Equals(value) != true)) {
                    this.identificativoField = value;
                    this.RaisePropertyChanged("identificativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PaesaggistaService.IPaesaggistaService")]
    public interface IPaesaggistaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaesaggistaService/findAll", ReplyAction="http://tempuri.org/IPaesaggistaService/findAllResponse")]
        Progetto.PaesaggistaService.paesaggista[] findAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaesaggistaService/findAll", ReplyAction="http://tempuri.org/IPaesaggistaService/findAllResponse")]
        System.Threading.Tasks.Task<Progetto.PaesaggistaService.paesaggista[]> findAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaesaggistaService/find", ReplyAction="http://tempuri.org/IPaesaggistaService/findResponse")]
        Progetto.PaesaggistaService.paesaggista find(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaesaggistaService/find", ReplyAction="http://tempuri.org/IPaesaggistaService/findResponse")]
        System.Threading.Tasks.Task<Progetto.PaesaggistaService.paesaggista> findAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaesaggistaService/Addpaes", ReplyAction="http://tempuri.org/IPaesaggistaService/AddpaesResponse")]
        void Addpaes(Progetto.PaesaggistaService.paesaggista paes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaesaggistaService/Addpaes", ReplyAction="http://tempuri.org/IPaesaggistaService/AddpaesResponse")]
        System.Threading.Tasks.Task AddpaesAsync(Progetto.PaesaggistaService.paesaggista paes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaesaggistaService/visemail", ReplyAction="http://tempuri.org/IPaesaggistaService/visemailResponse")]
        bool visemail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaesaggistaService/visemail", ReplyAction="http://tempuri.org/IPaesaggistaService/visemailResponse")]
        System.Threading.Tasks.Task<bool> visemailAsync(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaesaggistaServiceChannel : Progetto.PaesaggistaService.IPaesaggistaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaesaggistaServiceClient : System.ServiceModel.ClientBase<Progetto.PaesaggistaService.IPaesaggistaService>, Progetto.PaesaggistaService.IPaesaggistaService {
        
        public PaesaggistaServiceClient() {
        }
        
        public PaesaggistaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaesaggistaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaesaggistaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaesaggistaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Progetto.PaesaggistaService.paesaggista[] findAll() {
            return base.Channel.findAll();
        }
        
        public System.Threading.Tasks.Task<Progetto.PaesaggistaService.paesaggista[]> findAllAsync() {
            return base.Channel.findAllAsync();
        }
        
        public Progetto.PaesaggistaService.paesaggista find(int id) {
            return base.Channel.find(id);
        }
        
        public System.Threading.Tasks.Task<Progetto.PaesaggistaService.paesaggista> findAsync(int id) {
            return base.Channel.findAsync(id);
        }
        
        public void Addpaes(Progetto.PaesaggistaService.paesaggista paes) {
            base.Channel.Addpaes(paes);
        }
        
        public System.Threading.Tasks.Task AddpaesAsync(Progetto.PaesaggistaService.paesaggista paes) {
            return base.Channel.AddpaesAsync(paes);
        }
        
        public bool visemail(string email) {
            return base.Channel.visemail(email);
        }
        
        public System.Threading.Tasks.Task<bool> visemailAsync(string email) {
            return base.Channel.visemailAsync(email);
        }
    }
}
